# Generated by Django 5.0.6 on 2024-05-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Organization')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('country', models.CharField(verbose_name='Country')),
                ('city', models.CharField(verbose_name='City')),
                ('street', models.CharField(verbose_name='Street')),
                ('building_number', models.CharField(verbose_name='Building number')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Debt to supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comm_net_app.organization', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Product title')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer', to='comm_net_app.organization', verbose_name='Manufacturer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='comm_net_app.organization', verbose_name='Seller')),
            ],
        ),
    ]
