# Generated by Django 5.0.6 on 2024-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0002_remove_organization_supplier_organization_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='supplier',
            field=models.ManyToManyField(to='comm_net_app.organization', verbose_name='Supplier'),
        ),
    ]
