# Generated by Django 5.0.6 on 2024-05-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0003_alter_organization_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='debt',
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Debt to supplier')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='comm_net_app.organization', verbose_name='Debt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='comm_net_app.organization', verbose_name='Debtor')),
            ],
        ),
    ]
