# Generated by Django 5.0.6 on 2024-05-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0004_remove_organization_debt_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='comm_net_app.organization', verbose_name='Supplier'),
        ),
    ]
