# Generated by Django 5.0.6 on 2024-05-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0005_alter_debt_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='comm_net_app.organization', verbose_name='Organization'),
        ),
    ]
