# Generated by Django 5.0.6 on 2024-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0006_alter_debt_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='EMAIL'),
        ),
    ]
