# Generated by Django 5.0.6 on 2024-05-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0007_alter_organization_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='supplier',
            new_name='partner',
        ),
    ]
