# Generated by Django 5.0.6 on 2024-06-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_net_app', '0008_rename_supplier_organization_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='partner',
        ),
        migrations.AddField(
            model_name='organization',
            name='diller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='comm_net_app.organization', verbose_name='Diller'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dillers', to='comm_net_app.organization', verbose_name='Supplier'),
        ),
    ]
